#ifndef SEGMENTS_H
#define SEGMENTS_H

#define D0_SEGA (1 << 7)
#define D0_SEGB (1 << 6)
#define D0_SEGC (1 << 5)
#define D0_SEGD (1 << 4)
#define D0_SEGE (1 << 3)
#define D0_SEGF (1 << 1)
#define D0_SEGG (1 << 2)

#define D0_0 (D0_SEGA | D0_SEGB | D0_SEGC | D0_SEGD | D0_SEGE | D0_SEGF          )
#define D0_1 (          D0_SEGB | D0_SEGC                                        )
#define D0_2 (D0_SEGA | D0_SEGB           | D0_SEGD | D0_SEGE           | D0_SEGG)
#define D0_3 (D0_SEGA | D0_SEGB | D0_SEGC | D0_SEGD                     | D0_SEGG)
#define D0_4 (          D0_SEGB | D0_SEGC                     | D0_SEGF | D0_SEGG)
#define D0_5 (D0_SEGA           | D0_SEGC | D0_SEGD           | D0_SEGF | D0_SEGG)
#define D0_6 (D0_SEGA           | D0_SEGC | D0_SEGD | D0_SEGE | D0_SEGF | D0_SEGG)
#define D0_7 (D0_SEGA | D0_SEGB | D0_SEGC                                        )
#define D0_8 (D0_SEGA | D0_SEGB | D0_SEGC | D0_SEGD | D0_SEGE | D0_SEGF | D0_SEGG)
#define D0_9 (D0_SEGA | D0_SEGB | D0_SEGC | D0_SEGD           | D0_SEGF | D0_SEGG)
#define D0_A (D0_SEGA | D0_SEGB | D0_SEGC           | D0_SEGE | D0_SEGF | D0_SEGG)
#define D0_B (                    D0_SEGC | D0_SEGD | D0_SEGE | D0_SEGF | D0_SEGG)
#define D0_C (D0_SEGA                     | D0_SEGD | D0_SEGE | D0_SEGF          )
#define D0_D (          D0_SEGB | D0_SEGC | D0_SEGD | D0_SEGE           | D0_SEGG)
#define D0_E (D0_SEGA                     | D0_SEGD | D0_SEGE | D0_SEGF | D0_SEGG)
#define D0_F (D0_SEGA                               | D0_SEGE | D0_SEGF | D0_SEGG)

#define D1_SEGA (1 << 2)
#define D1_SEGB (1 << 1)
#define D1_SEGC (1 << 0)
#define D1_SEGD (1 << 5)
#define D1_SEGE (1 << 6)
#define D1_SEGF (1 << 3)
#define D1_SEGG (1 << 7)

#define D1_0 (D1_SEGA | D1_SEGB | D1_SEGC | D1_SEGD | D1_SEGE | D1_SEGF          )
#define D1_1 (          D1_SEGB | D1_SEGC                                        )
#define D1_2 (D1_SEGA | D1_SEGB           | D1_SEGD | D1_SEGE           | D1_SEGG)
#define D1_3 (D1_SEGA | D1_SEGB | D1_SEGC | D1_SEGD                     | D1_SEGG)
#define D1_4 (          D1_SEGB | D1_SEGC                     | D1_SEGF | D1_SEGG)
#define D1_5 (D1_SEGA           | D1_SEGC | D1_SEGD           | D1_SEGF | D1_SEGG)
#define D1_6 (D1_SEGA           | D1_SEGC | D1_SEGD | D1_SEGE | D1_SEGF | D1_SEGG)
#define D1_7 (D1_SEGA | D1_SEGB | D1_SEGC                                        )
#define D1_8 (D1_SEGA | D1_SEGB | D1_SEGC | D1_SEGD | D1_SEGE | D1_SEGF | D1_SEGG)
#define D1_9 (D1_SEGA | D1_SEGB | D1_SEGC | D1_SEGD           | D1_SEGF | D1_SEGG)
#define D1_A (D1_SEGA | D1_SEGB | D1_SEGC           | D1_SEGE | D1_SEGF | D1_SEGG)
#define D1_B (                    D1_SEGC | D1_SEGD | D1_SEGE | D1_SEGF | D1_SEGG)
#define D1_C (D1_SEGA                     | D1_SEGD | D1_SEGE | D1_SEGF          )
#define D1_D (          D1_SEGB | D1_SEGC | D1_SEGD | D1_SEGE           | D1_SEGG)
#define D1_E (D1_SEGA                     | D1_SEGD | D1_SEGE | D1_SEGF | D1_SEGG)
#define D1_F (D1_SEGA                               | D1_SEGE | D1_SEGF | D1_SEGG)


#endif
